### PR TITLE
fix imports for newer prompt-toolkit

### PR DESCRIPTION
**Pull request by superkhung**
didn't see any more error so far (history, completion, interface ...)

### CODE REVIEW

**Comment by oleavr** [comment]
Sweet! Could you also update setup.py and squash your commits?

**Comment by superkhung** [comment]
updated setup.py to use prompt-toolkit >= 0.57 and squash commits

**Comment by oleavr** [comment]
Thanks! One final thing, could you also please adjust the commit messages for consistency? We're following this style:
http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
For these two commits you're almost there already, just need to capitalize the first letter of each. :)

**Comment by superkhung** [comment]
Added capitalize :)

**Comment by oleavr** [comment]
Thanks! :)

**Pull request merged**
